[workspace]
resolver = "2"
members = ["./layershellev", "./starcolorkeyboard", "./sessionlockev"]

[workspace.package]
authors = [
	"Decodertalkers <aakari@tutanota.com>",
	"Aakash Sen Sharma <aakashsensharma@gmail.com>",
]
edition = "2021"
version = "0.1.0"
license = "MIT"
description = "Wayland extra shell lib"
keywords = ["wayland"]

[workspace.dependencies]
layershellev = { version = "0.1.0", path = "./layershellev" }
sessionlockev = { version = "0.1.0", path = "./sessionlockev" }
